# Generated by Django 6.0.5 on 2026-05-31 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_multiplier', models.FloatField(default=1.0)),
                ('xp_decay_rate', models.FloatField(default=0.0)),
                ('event_multiplier', models.FloatField(default=1.5)),
                ('explorer_milestone', models.IntegerField(default=1000)),
                ('champion_milestone', models.IntegerField(default=3000)),
                ('legend_milestone', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=200)),
                ('xp_reward', models.IntegerField(default=100)),
                ('due_date', models.CharField(max_length=100)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('questions', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=200)),
                ('instructor_avatar', models.CharField(max_length=500)),
                ('progress_percent', models.IntegerField(default=0)),
                ('students_count', models.IntegerField(default=0)),
                ('new_activities_count', models.IntegerField(default=0)),
                ('image_url', models.CharField(max_length=500)),
                ('room_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_initials', models.CharField(max_length=20)),
                ('student_avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('quiz_title', models.CharField(max_length=200)),
                ('submitted_time', models.CharField(max_length=200)),
                ('status', models.CharField(default='READY', max_length=50)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='student', max_length=20)),
                ('xp', models.IntegerField(default=1250)),
                ('streak', models.IntegerField(default=4)),
                ('streak_freeze_count', models.IntegerField(default=2)),
                ('streak_freeze_active', models.BooleanField(default=False)),
                ('avatar', models.CharField(default='https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200&h=200', max_length=500)),
                ('badges', models.JSONField(default=list)),
                ('daily_mission_progress', models.IntegerField(default=2)),
                ('daily_mission_completed', models.BooleanField(default=False)),
                ('daily_mission_claimed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
